# Generated by Django 3.1.7 on 2021-04-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, height_field=150, max_length=200, null=True, upload_to='images', width_field=150),
        ),
    ]
