# Generated by Django 3.1.7 on 2021-04-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210412_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='number_of_bids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
