# Generated by Django 3.1.7 on 2021-04-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_bid_number_of_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='item',
            new_name='listing',
        ),
    ]
