# Generated by Django 3.1.7 on 2021-04-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210414_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='time',
            new_name='created_on',
        ),
    ]
