# Generated by Django 3.1.7 on 2021-04-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210405_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='base_Price',
            new_name='base_price',
        ),
    ]
