# Generated by Django 3.1.7 on 2021-04-05 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210405_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['-posting_date']},
        ),
        migrations.RemoveField(
            model_name='auction',
            name='start_date',
        ),
        migrations.AddField(
            model_name='auction',
            name='posting_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, default='no category', max_length=100),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Active'), (1, 'Closed')], default=0),
        ),
    ]
