# Generated by Django 3.1.7 on 2021-04-05 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210405_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='close_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='posting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
