# Generated by Django 3.1.7 on 2021-04-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210405_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['-posting_date']},
        ),
    ]
