# Generated by Django 3.1.7 on 2021-04-05 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210405_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='name',
            new_name='item_name',
        ),
    ]
