# Generated by Django 3.1.7 on 2021-04-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210405_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='name',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
