# Generated by Django 3.1.7 on 2021-05-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210428_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='item_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='auction',
            index_together={('id', 'slug')},
        ),
    ]
